### Update Score
POST http://localhost:3001/api/scores
Content-Type: application/json

{
    "userId": "exampleUser123",
    "scoreIncrease": 10,
    "authToken": "exampleAuthToken"
}

### Get Top Scores
GET http://localhost:3001/api/scores/top
