@token = token
@baseUrl = http://localhost:3000
### Register User
POST {{baseUrl}}/api/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@example.com",
  "password": "password123"
}

### Login User
# @name  loginrequest
POST {{baseUrl}}/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "johndoe@example.com",
  "password": "password123"
}
###
@token = {{loginrequest.response.body.$.token}}
### Get User Profile
GET {{baseUrl}}/api/users/profile HTTP/1.1
Authorization: Bearer {{token}}

### Delete User Profile
DELETE {{baseUrl}}/api/users/profile HTTP/1.1
Authorization: Bearer {{token}}


### Update Score
PUT {{baseUrl}}/api/scores
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "score": 10
}

### Get Top Scores
GET {{baseUrl}}/api/scores/top
Authorization: Bearer {{token}}

### Get Resources
GET {{baseUrl}}/api/resources?description=description HTTP/1.1
Content-Type: application/json

### Create Resource
POST {{baseUrl}}/api/resources HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "resource2",
  "description": "description2"
}

### Update Resource
PUT {{baseUrl}}/api/resources/678e7fd16ab2e3b0a515002b HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "resource updated",
  "description": "description1 updated"
}

### Delete Resource
DELETE  {{baseUrl}}/api/resources/678e7fd16ab2e3b0a515002b HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json